- title: "OSD - opensensorsdata srl"
  url: "/about"
  id: "about"
  text: 'dal 2015 progetta e realizza modelli di gestione e di business dei dati.'
- title: "Data management"
  url: "/gestire-i-dati/"
  id: "Gestire-dati"
  text: "gestiamo con infrastrutture leggere e modulari i dati documentali, fotografici e geografici di archivi pubblici e aziendali."
- title: "Open business model"
  url: "/open-business-model/"
  id: "open-business-model"
  text: "creiamo dei modelli che usano la distribuzione aperta e selezionata dei dati dei nostri clienti per aprire nuovi mercati e attrarre nuovi clienti."
- title: "Consulenza filosofica"
  url: "/consulenza-filosofica/"
  id: "consulenza-filosofica"
  text: "Aiutamo i nostri clienti a raggiungere un livello ottimale di analisi e di chiarezza nel ragionamento , per comprendere e gestire problemi complessi."
- title: "Innovazione e imprecazione"
  url: "https://www.spreaker.com/user/innovazione-imprecazione"
  id: "innovazione-imprecazione"
  text: "Il podcast di OSD per tutti quelli che hanno detto almeno una volta della vita <i>Maledetta innovazione!</i>"
